import "./globals.css";

export const metadata = {
  title: "Trello 2.0 AI Clone",
  description: "Generated by Rajvardhan Sing Dodiya",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}
